<a href="https://colab.research.google.com/github/Belloy96/K-Digital-Training/blob/master/Jul31_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 함수

# 하나의 array에 적용 (단항 유니버셜함수)

유니버셜함수 : ndarray안에 있는 데이터의 요소별로 연산을 수행해주는 함수

In [1]:
import numpy as np

ar1 = np.random.randn(5, 3)
ar1

array([[-5.03286606e-01,  1.76769243e-01, -3.49843775e-01],
       [ 8.77516592e-02, -7.79176717e-01,  7.34045487e-01],
       [-2.24487866e+00,  2.18453918e-01,  6.40158426e-01],
       [ 1.31313176e+00, -1.83613677e-05, -4.47733860e-01],
       [-8.81994740e-01, -8.07742327e-01, -6.15021999e-01]])

In [3]:
# 각 요소의 절대값
np.abs(ar1)

array([[5.03286606e-01, 1.76769243e-01, 3.49843775e-01],
       [8.77516592e-02, 7.79176717e-01, 7.34045487e-01],
       [2.24487866e+00, 2.18453918e-01, 6.40158426e-01],
       [1.31313176e+00, 1.83613677e-05, 4.47733860e-01],
       [8.81994740e-01, 8.07742327e-01, 6.15021999e-01]])

In [5]:
# 각 요소의 제곱근 계산 ( == ar1 ** 0.5 )
np.sqrt(ar1)

<ipython-input-5-6729b89e7ee3>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(ar1)


array([[       nan, 0.42043935,        nan],
       [0.29622907,        nan, 0.85676455],
       [       nan, 0.46739054, 0.80009901],
       [1.14591961,        nan,        nan],
       [       nan,        nan,        nan]])

In [6]:
# 각 요소의 제곱 계산
np.square(ar1)

array([[2.53297408e-01, 3.12473653e-02, 1.22390667e-01],
       [7.70035369e-03, 6.07116356e-01, 5.38822777e-01],
       [5.03948022e+00, 4.77221145e-02, 4.09802810e-01],
       [1.72431502e+00, 3.37139824e-10, 2.00465610e-01],
       [7.77914722e-01, 6.52447667e-01, 3.78252059e-01]])

In [7]:
# 각 요소를 자연로그, 상용로그, 아래가 2인 로그를 씌운 값 계산
print(np.log(ar1))
print()
print(np.log10(ar1))
print()
print(np.log2(ar1))

[[        nan -1.73291011         nan]
 [-2.43324451         nan -0.30918428]
 [        nan -1.52118019 -0.44603959]
 [ 0.27241494         nan         nan]
 [        nan         nan         nan]]

[[        nan -0.7525933          nan]
 [-1.05674466         nan -0.13427703]
 [        nan -0.66064016 -0.19371253]
 [ 0.11830831         nan         nan]
 [        nan         nan         nan]]

[[        nan -2.50006082         nan]
 [-3.51042979         nan -0.44605863]
 [        nan -2.19459911 -0.64349911]
 [ 0.39301168         nan         nan]
 [        nan         nan         nan]]


<ipython-input-7-9ac07f5d57b3>:2: RuntimeWarning: invalid value encountered in log
  print(np.log(ar1))
<ipython-input-7-9ac07f5d57b3>:4: RuntimeWarning: invalid value encountered in log10
  print(np.log10(ar1))
<ipython-input-7-9ac07f5d57b3>:6: RuntimeWarning: invalid value encountered in log2
  print(np.log2(ar1))


In [8]:
# 각 요소의 부호 나타내기 (+ : 1, - : -1, 0 : 0)
np.sign(ar1)

array([[-1.,  1., -1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1., -1., -1.],
       [-1., -1., -1.]])

In [9]:
# 각 요소의 소수 첫 번째 자리에서 올림한 값 계산
np.ceil(ar1)

array([[-0.,  1., -0.],
       [ 1., -0.,  1.],
       [-2.,  1.,  1.],
       [ 2., -0., -0.],
       [-0., -0., -0.]])

In [10]:
# 각 요소의 소수 첫 번째 자리에서 버림한 값 계산
np.floor(ar1)

array([[-1.,  0., -1.],
       [ 0., -1.,  0.],
       [-3.,  0.,  0.],
       [ 1., -1., -1.],
       [-1., -1., -1.]])

In [11]:
# 각 요소의 소수 첫 번째 자리에서 반올림한 값 계산
np.round(ar1)

array([[-1.,  0., -0.],
       [ 0., -1.,  1.],
       [-2.,  0.,  1.],
       [ 1., -0., -0.],
       [-1., -1., -1.]])

In [12]:
# 각 요소의 nan인 경우 True, 아닌 경우 False를 반환
np.isnan(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [13]:
# 각 요소가 무한대인 경우 True, 아닌 경우 False를 반환
np.isinf(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [14]:
# 각 요소에 대해 삼각함수(+ 쌍곡선) 값을 계산하기 (cos, cosh ,sin, sinh, tan, tanh)
# ~h : 쌍곡선 함수
# 쌍곡선 : 고정된 두 초점으로부터 거리가 일정한 점들에 의해 나타나는 곡선
np.cos(ar1)

array([[ 0.87600214,  0.98441696,  0.93942627],
       [ 0.99615229,  0.7114923 ,  0.7424705 ],
       [-0.62418063,  0.97623368,  0.80200114],
       [ 0.25482291,  1.        ,  0.90143048],
       [ 0.63561245,  0.69113188,  0.81676075]])

# 두 개의 array에 적용 (이항 유니버셜함수)

In [15]:
ar1

array([[-5.03286606e-01,  1.76769243e-01, -3.49843775e-01],
       [ 8.77516592e-02, -7.79176717e-01,  7.34045487e-01],
       [-2.24487866e+00,  2.18453918e-01,  6.40158426e-01],
       [ 1.31313176e+00, -1.83613677e-05, -4.47733860e-01],
       [-8.81994740e-01, -8.07742327e-01, -6.15021999e-01]])

In [16]:
ar2 = np.random.randn(5, 3)
ar2

array([[-0.49323498, -2.11612115,  0.74850778],
       [ 1.96477177, -1.66746687,  0.30845227],
       [-0.42448164,  0.66556281,  0.44114394],
       [ 0.62427362,  0.96370447, -0.3288338 ],
       [ 0.02429834,  1.34134458,  0.94497499]])

In [17]:
# 두 개의 array에 대해 동일한 위치 요소끼리
# 연산 값을 계산함수 (add, subtract, multiply, divide)
np.multiply(ar1, ar2)

array([[ 2.48238558e-01, -3.74065133e-01, -2.61860787e-01],
       [ 1.72411983e-01,  1.29925136e+00,  2.26417994e-01],
       [ 9.52909778e-01,  1.45394803e-01,  2.82402012e-01],
       [ 8.19753512e-01, -1.76949321e-05,  1.47230029e-01],
       [-2.14310112e-02, -1.08346079e+00, -5.81180404e-01]])

In [18]:
# 두 개의 array에 대해 동일한 위치의 요소끼리 비교해서 최대값 or 최소값 계산
#   (maximum, minimum)
np.maximum(ar1, ar2)

array([[-0.49323498,  0.17676924,  0.74850778],
       [ 1.96477177, -0.77917672,  0.73404549],
       [-0.42448164,  0.66556281,  0.64015843],
       [ 1.31313176,  0.96370447, -0.3288338 ],
       [ 0.02429834,  1.34134458,  0.94497499]])

# 통계 함수

통계 함수를 통해서 array의 합이나 평균 등을 구할 때

추가로 'axis'라는 파라미터에 대한 값을 지정해서(axis -> 축)

열 또는 행의 합 또는 평균 등을 구할 수 있음 !

In [19]:
# 열 간의 합을 계산
np.sum(ar1, axis=0) # Numpy에서 열을 의미하는 값은 0 값임

array([-2.22927659, -1.19171424, -0.03839572])

In [20]:
# 행 간의 합을 계산
np.sum(ar1, axis=1) # Numpy에서 행을 의미하는 값은 1 값임

array([-0.67636114,  0.04262043, -1.38626632,  0.86537954, -2.30475907])

In [21]:
# 전체 요소의 평균을 계산
np.mean(ar1)

-0.23062577052939043

In [23]:
# 전체 요소의 표준편차, 분산, 최소값, 최대값 (std, var, min, max)
# 표준편차 : 데이터가 평균으로부터 얼마나 흩어있는지를 나타내는 지표
# 분산 : 데이터가 평균으로부터 얼마나 멀리 떨어져있는지를 측정하는 지표
#   (분산이 크면 평균으로부터 데이터들이 멀리 있고, 아니면 평균과 가까이 모여있음을 의미)
np.std(ar1)

-2.2448786639552143

In [24]:
# 전체 요소의 최소값, 최대값이 위치한 인덱스의 위치를 반환 (argmin, argmax)
np.argmin(ar1)

6

In [25]:
# 맨 처음 요소부터 각 요소까지의 누적합 or 누적곱을 계산 (cumsum, cumprod)
np.cumsum(ar1)

array([-0.50328661, -0.32651736, -0.67636114, -0.58860948, -1.3677862 ,
       -0.63374071, -2.87861937, -2.66016545, -2.02000703, -0.70687527,
       -0.70689363, -1.15462749, -2.03662223, -2.84436456, -3.45938656])

In [31]:
# 사분위수 : 사분위수는 데이터를 4등분 한 것
# 0 ~ 1 을 4등분(25%씩). 1/4분위수, 2/4분위수(중앙값 이라고도 표현), 3/4분위수, 4/4분위수

# 0.25 : 1 사분위수 / 0.5 : 2 사분위수 (중앙값) / 0.75 : 3 사분위
np.quantile(ar1, [0.25, 0.5, 0.75])

array([-0.69709936, -0.34984378,  0.19761158])

# 기타 함수

In [26]:
# 전체 요소에 대해서 오름차순 정렬
np.sort(ar1)

array([[-5.03286606e-01, -3.49843775e-01,  1.76769243e-01],
       [-7.79176717e-01,  8.77516592e-02,  7.34045487e-01],
       [-2.24487866e+00,  2.18453918e-01,  6.40158426e-01],
       [-4.47733860e-01, -1.83613677e-05,  1.31313176e+00],
       [-8.81994740e-01, -8.07742327e-01, -6.15021999e-01]])

In [29]:
# 열 방향으로 오름차순 정렬
np.sort(ar1, axis=0)

array([[-0.49323498, -2.11612115, -0.3288338 ],
       [-0.42448164, -1.66746687,  0.30845227],
       [ 0.02429834,  0.66556281,  0.44114394],
       [ 0.62427362,  0.96370447,  0.74850778],
       [ 1.96477177,  1.34134458,  0.94497499]])

In [30]:
# zip 함수
# 각 객체들을 파라미터로 받고, 그 요소들을 tuple의 형태로 반환
numbers = [1, 2, 3]
letters = ['A', 'B', 'C']
for pair in zip(numbers, letters):
  print(pair)

(1, 'A')
(2, 'B')
(3, 'C')
